name = "FiniteStateAutomata"
uuid = "fc9063f0-9721-496a-abcf-7f8e825377b5"
authors = ["Lucas ONDEL YANG <lucas.ondel@cnrs.fr"]
version = "0.2.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
